/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Challenge {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export type GameMode = { 'solo' : null } |
  { 'competitive' : null } |
  { 'cooperative' : null };
export interface LeaderboardEntry {
  'player' : Principal,
  'wins' : bigint,
  'totalScore' : bigint,
}
export interface LobbyView {
  'id' : bigint,
  'currentChallenge' : [] | [Challenge],
  'host' : Principal,
  'mode' : GameMode,
  'isActive' : boolean,
  'players' : Array<Principal>,
}
export interface MatchResultView {
  'scores' : Array<[Principal, bigint]>,
  'mode' : GameMode,
  'winner' : [] | [Principal],
  'matchId' : bigint,
  'timestamp' : Time,
}
export interface TerminalOutput {
  'context' : [] | [string],
  'solved' : boolean,
  'lines' : Array<string>,
}
export type Time = bigint;
export interface UserProfile {
  'gamesPlayed' : bigint,
  'name' : string,
  'totalScore' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLobby' : ActorMethod<[GameMode], bigint>,
  'getActiveLobbies' : ActorMethod<[], Array<LobbyView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getLobby' : ActorMethod<[bigint], [] | [LobbyView]>,
  'getRecentMatches' : ActorMethod<[], Array<MatchResultView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinLobby' : ActorMethod<[bigint], undefined>,
  'leaveLobby' : ActorMethod<[bigint], undefined>,
  'processTerminalCommand' : ActorMethod<[bigint, string], TerminalOutput>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startMatch' : ActorMethod<[bigint], undefined>,
  'startMatchAndGetLobby' : ActorMethod<[bigint], [] | [LobbyView]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];