/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameMode = IDL.Variant({
  'solo' : IDL.Null,
  'competitive' : IDL.Null,
  'cooperative' : IDL.Null,
});
export const Challenge = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const LobbyView = IDL.Record({
  'id' : IDL.Nat,
  'currentChallenge' : IDL.Opt(Challenge),
  'host' : IDL.Principal,
  'mode' : GameMode,
  'isActive' : IDL.Bool,
  'players' : IDL.Vec(IDL.Principal),
});
export const UserProfile = IDL.Record({
  'gamesPlayed' : IDL.Nat,
  'name' : IDL.Text,
  'totalScore' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'player' : IDL.Principal,
  'wins' : IDL.Nat,
  'totalScore' : IDL.Nat,
});
export const Time = IDL.Int;
export const MatchResultView = IDL.Record({
  'scores' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
  'mode' : GameMode,
  'winner' : IDL.Opt(IDL.Principal),
  'matchId' : IDL.Nat,
  'timestamp' : Time,
});
export const TerminalOutput = IDL.Record({
  'context' : IDL.Opt(IDL.Text),
  'solved' : IDL.Bool,
  'lines' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLobby' : IDL.Func([GameMode], [IDL.Nat], []),
  'getActiveLobbies' : IDL.Func([], [IDL.Vec(LobbyView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getLobby' : IDL.Func([IDL.Nat], [IDL.Opt(LobbyView)], ['query']),
  'getRecentMatches' : IDL.Func([], [IDL.Vec(MatchResultView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinLobby' : IDL.Func([IDL.Nat], [], []),
  'leaveLobby' : IDL.Func([IDL.Nat], [], []),
  'processTerminalCommand' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [TerminalOutput],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startMatch' : IDL.Func([IDL.Nat], [], []),
  'startMatchAndGetLobby' : IDL.Func([IDL.Nat], [IDL.Opt(LobbyView)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameMode = IDL.Variant({
    'solo' : IDL.Null,
    'competitive' : IDL.Null,
    'cooperative' : IDL.Null,
  });
  const Challenge = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const LobbyView = IDL.Record({
    'id' : IDL.Nat,
    'currentChallenge' : IDL.Opt(Challenge),
    'host' : IDL.Principal,
    'mode' : GameMode,
    'isActive' : IDL.Bool,
    'players' : IDL.Vec(IDL.Principal),
  });
  const UserProfile = IDL.Record({
    'gamesPlayed' : IDL.Nat,
    'name' : IDL.Text,
    'totalScore' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'player' : IDL.Principal,
    'wins' : IDL.Nat,
    'totalScore' : IDL.Nat,
  });
  const Time = IDL.Int;
  const MatchResultView = IDL.Record({
    'scores' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
    'mode' : GameMode,
    'winner' : IDL.Opt(IDL.Principal),
    'matchId' : IDL.Nat,
    'timestamp' : Time,
  });
  const TerminalOutput = IDL.Record({
    'context' : IDL.Opt(IDL.Text),
    'solved' : IDL.Bool,
    'lines' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLobby' : IDL.Func([GameMode], [IDL.Nat], []),
    'getActiveLobbies' : IDL.Func([], [IDL.Vec(LobbyView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getLobby' : IDL.Func([IDL.Nat], [IDL.Opt(LobbyView)], ['query']),
    'getRecentMatches' : IDL.Func([], [IDL.Vec(MatchResultView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinLobby' : IDL.Func([IDL.Nat], [], []),
    'leaveLobby' : IDL.Func([IDL.Nat], [], []),
    'processTerminalCommand' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [TerminalOutput],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startMatch' : IDL.Func([IDL.Nat], [], []),
    'startMatchAndGetLobby' : IDL.Func([IDL.Nat], [IDL.Opt(LobbyView)], []),
  });
};

export const init = ({ IDL }) => { return []; };